const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { spawnSync } = require('node:child_process')

test('reality diagnostic guides a template repair while preserving unrelated doctor failures', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'fde-reality-guidance-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const eng = path.join(root, '.fde'); fs.mkdirSync(eng)
  fs.writeFileSync(path.join(eng, 'context.md'), '# Context\n**Phase:** plan\n')
  const values = ['Retries bypass the batch guard.', 'Replay log shows two sends.', 'The guard needs repair before a new dashboard.']
  fs.writeFileSync(path.join(eng, 'reality.md'), '# Reality\n## Working theory\n' + values[0] + '\n## Evidence\n' + values[1] + '\n## Differs from brief\n' + values[2] + '\n<private>REALITY_PRIVATE_SENTINEL</private>\n')
  const run = () => spawnSync(process.execPath, [path.resolve(__dirname, '../bin/fde.js'), 'doctor'], { cwd: root, env: { ...process.env, HOME: root, FDEOPS_ENGAGEMENT: eng, FDEOPS_ENGAGEMENTS_ROOT: root }, encoding: 'utf8' })
  const before = run()
  assert.notEqual(before.status, 0)
  const diagnostic = before.stdout.split('\n').find(line => line.includes('reality.md does not match the schema'))
  assert.ok(diagnostic, before.stdout)
  assert.match(diagnostic, /templates\/\.fde\/reality\.md/)
  const template = fs.readFileSync(path.resolve(__dirname, '../templates/.fde/reality.md'), 'utf8')
  const fields = template.match(/^\*\*(?:Working theory|Evidence|Differs from brief how):\*\*$/gm)
  assert.equal(fields.length, 3)
  const audit = fs.readFileSync(path.resolve(__dirname, '../skills/fde/references/audit.md'), 'utf8')
  const guidance = audit.split('\n').find(line => line.startsWith('**`reality.md`**'))
  assert.ok(guidance)
  for (const field of fields) {
    assert.ok(diagnostic.includes(field), field)
    assert.ok(guidance.includes(field), field)
  }
  assert.doesNotMatch(guidance, /\]\([^)]*templates\//)
  for (const value of [...values, 'REALITY_PRIVATE_SENTINEL']) assert.ok(!diagnostic.includes(value), value)
  assert.match(before.stdout, /empty operating map/)
  const repaired = '# Reality\n' + fields.map((field, i) => field + ' ' + values[i]).join('\n') + '\n'
  fs.writeFileSync(path.join(eng, 'reality.md'), repaired)
  const after = run()
  assert.notEqual(after.status, 0)
  assert.doesNotMatch(after.stdout, /reality.md does not match the schema/)
  assert.match(after.stdout, /empty operating map/)
  assert.equal(fs.readFileSync(path.join(eng, 'reality.md'), 'utf8'), repaired)
  const issueLines = text => text.split('\n').filter(line => /^\s*\d+\./.test(line)).map(line => line.replace(/^\s*\d+\./, '').trim())
  assert.deepEqual(issueLines(after.stdout), issueLines(before.stdout).filter(line => !line.includes('reality.md does not match the schema')))
})
